GET http://localhost:3002/api/blogs


###
POST http://localhost:3002/api/blogs
Content-Type: application/json

{
  "url": "noAuthor2.com",
  "title": "this WILL work"
}


###
DELETE http://localhost:3002/api/blogs/2
