GET http://localhost:3001/api/blogs

###
GET http://localhost:3001/api/blogs/10


###
PUT http://localhost:3001/api/blogs/2323230943
Content-Type: application/json

{
  "url": "noAuthor3.com",
  "title": "this WILL work hopefully for id3"
}


###
DELETE http://localhost:3001/api/blogs/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlY29uZFVzZXJAZ21haS5jb20iLCJpZCI6MywiaWF0IjoxNzc1MDU0NTg1fQ.vE0BnrBsNN21BZwjx7hE57GpvKTsZkZOyTCDIycmTpA



###
POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRvY2tlcjJAZ21haS5jb20iLCJpZCI6MiwiaWF0IjoxNzc1MTMyOTYyfQ.4FDMqRALarMF-iYY9_55jQragKlLVhpRUreVKSx6hiU

{
  "title": "second postgres blog",
  "author": "docker",
  "url": "dockerexec1.com",
  "likes": 19
}
