GET http://localhost:3001/api/users


###
GET http://localhost:3001/


###
POST http://localhost:3001/api/reset


###
DELETE http://localhost:3001/api/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlc3Npb25AZXhhbXBsZS5jb20iLCJpZCI6MywiaWF0IjoxNzc2MTA3OTc3fQ.LxpoQAYiXeY0xE4p87zNgIjkSsslklwje_QCgmbyejM
