GET http://localhost:3001/api/users

###
PUT http://localhost:3001/api/users/testing_Hash
Content-Type: application/json

{
  "username": "hashUser11"
}



###
POST http://localhost:3001/api/users/
Content-Type: application/json

{
  "name": "postgresUser2",
  "username": "docker2@gmai.com",
  "password": "docker2"
}
